services:
  article.controller.factory:
    class: CW\Controller\EntityControllerFactory
    arguments:
      - @identity-map
      - @object-loader.drupal
      - 'CWExample\Controller\ArticleController'
      - 'CWExample\Model\ArticleModel'
      - 'node'
