services:
  cw.article.controller.factory:
    class: CW\Controller\EntityControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-loader.drupal
      - 'CWExample\Controller\ArticleController'
      - 'CWExample\Model\ArticleModel'
      - 'node'
