id: d6_search_settings
source:
    plugin: drupal6_variable
    variables:
        - minimum_word_size
        - overlap_cjk
        - search_cron_limit
        - search_tag_weights
        - search_and_or_limit
process:
    'index:minimum_word_size': minimum_word_size
    'index:overlap_cjk': overlap_cjk
    'index:cron_limit': search_cron_limit
destination:
    plugin: d8_config
    config_name: search.settings
