id: d6_taxonomy_settings
source:
  plugin: drupal6_variable
  variables:
    - taxonomy_override_selector
    - taxonomy_terms_per_page_admin
process:
  override_selector: taxonomy_override_selector
  terms_per_page_admin: taxonomy_terms_per_page_admin
destination:
  plugin: d8_config
  config_name: taxonomy.settings
