id: d6_locale_settings
source:
  plugin: drupal6_variable
  variables:
    - locale_cache_strings
    - locale_js_directory
process:
  cache_string: locale_cache_strings
  'javascript:directory': locale_js_directory
destination:
  plugin: d8_config
  config_name: locale.settings
