id: d6_system_file
source:
  plugin: drupal6_variable
  variables:
    - file_directory_path
    - file_directory_temp
process:
  'path:private': file_directory_path
  'path:temporary': file_directory_temp
destination:
  plugin: d8_config
  config_name: system.file
