id: d6_file_settings
source:
  plugin: drupal6_variable
  variables:
    - file_description_type
    - file_description_length
    - file_icon_directory
process:
  'description:type': file_description_type
  'description:length': file_description_length
  'icon:directory': file_icon_directory
destination:
  plugin: d8_config
  config_name: file.settings
