id: d6_system_maintenance
source:
  plugin: drupal6_variable
  variables:
    - site_offline
    - site_offline_message
process:
  enable: site_offline
  message: site_offline_message
destination:
  plugin: d8_config
  config_name: system.maintenance
