sudo: false

language: php

mysql:
  database: drupal
  username: root
  encoding: utf8

php:
  - 5.5

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update
  - composer global require drush/drush:7.*

before_script:
  - composer install
  - mysql -e 'create database drupal'
  - cd ..
  - drush dl drupal -y
  - cd drupal-*
  - drush si minimal --db-url=mysql://root:@localhost/drupal -y
  - ln -s /home/travis/build/cameronandwilding/CWTool ./sites/all/modules/cwtool
  - drush dl ctools drupal_psr_cache drupal_psr3 entity entityreference references features strongarm -y
  - composer install -d sites/all/modules/drupal_psr3
  - composer install -d sites/all/modules/drupal_psr_cache
  - drush en cw_tool simpletest -y
  - cd /home/travis/build/cameronandwilding/CWTool

script:
  - phpunit -c phpunit.xml
  - cd ../drupal-*/
  - drush runserver 127.0.0.1:8080 &
  - php ./scripts/run-tests.sh --verbose --php /home/travis/.phpenv/shims/php --url http://127.0.0.1:8080 CW
