<?php
/**
 * @file
 *
 * Helper functions.
 */

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/includes/cw_tool.content.inc';
require_once __DIR__ . '/includes/cw_tool.util.inc';

/**
 * Get the dependency injection container.
 *
 * @return \Symfony\Component\DependencyInjection\ContainerBuilder
 */
function cw_tool_get_container() {
  static $container;

  if (!empty($container)) {
    return $container;
  }

  // @todo add weight so it's sortable
  $containerConfigs = new \CW\Util\ServiceContainerDefinitionCollection();
  $containerConfigs->add(__DIR__ . '/config');
  drupal_alter('cw_tool_service_container_definition', $containerConfigs);

  $container = new ContainerBuilder();

  foreach ($containerConfigs->getConfigs() as $containerConfig) {
    $locator = new FileLocator(array($containerConfig));
    $loader = new YamlFileLoader($container, $locator);
    $loader->load('services.yml');
  }

  $container->compile();

  return $container;
}
