<?php
/**
 * @file
 *
 * Helper functions.
 */

use CW\Form\VariableFormGenerator;
use CW\Manager\VariableManager;
use CW\Util\CronTimer;
use CW\Util\SimpleList;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/includes/cw_tool.content.inc';
require_once __DIR__ . '/includes/cw_tool.util.inc';

// Service names.
define('CWTOOL_SERVICE_NODE_FACTORY', 'cw.node-controller.factory');
define('CWTOOL_SERVICE_USER_FACTORY', 'cw.user-controller.factory');
define('CWTOOL_SERVICE_VARIABLE_MANAGER', 'cw.variable-manager');
define('CWTOOL_SERVICE_VARIABLE_ADAPTER', 'cw.variable-adapter');
define('CWTOOL_SERVICE_CRON_TIMER', 'cw.cron-timer');

/**
 * Get the dependency injection container.
 *
 * @return \Symfony\Component\DependencyInjection\ContainerBuilder
 */
function cw_tool_get_container() {
  static $container;

  if (!empty($container)) {
    return $container;
  }

  // @todo add weight so it's sortable
  $containerConfigs = new SimpleList();
  $containerConfigs->add(__DIR__ . '/config');
  drupal_alter('cw_tool_service_container_definition', $containerConfigs);

  $container = new ContainerBuilder();

  foreach ($containerConfigs->getAll() as $containerConfig) {
    $locator = new FileLocator(array($containerConfig));
    $loader = new YamlFileLoader($container, $locator);
    $loader->load('services.yml');
  }

  $container->compile();

  return $container;
}

/**
 * Implements hook_menu().
 */
function cw_tool_menu() {
  return array(
    // Admin section.
    'admin/config/application' => array(
      'title' => 'Application settings',
      'description' => 'Application settings.',
      'position' => 'left',
      'weight' => -10,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file' => 'system.admin.inc',
    ),

    // Variable settings page.
    'admin/config/application/variables' => array(
      'title' => 'Variables',
      'description' => 'Environment app variables.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cw_tool_core_admin_settings_form'),
      'access arguments' => array('access administration pages'),
    ),
  );
}

function cw_tool_core_admin_settings_form($form) {
  /** @var VariableManager $variableManager */
  $variableManager = cw_tool_get_container()->get(CWTOOL_SERVICE_VARIABLE_MANAGER);
  $variableManager->collectAppVariables();
  $variablesForm = new VariableFormGenerator($variableManager);
  return $variablesForm->generateForm($form);
}

/**
 * @return CronTimer
 */
function cw_tool_cron_timer() {
  return cw_tool_get_container()->get(CWTOOL_SERVICE_CRON_TIMER);
}