<?php
/**
 * @file
 * Install routines for checklist module.
 */
/**
 * Implements hook_schema().
 */
function checklist_schema() {
  $schema['checklist_item'] = array(
    'description' => 'Stores checklist items.',
    'fields' => array(
      'ciid' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique checklist item ID.',
      ),
      'uuid' => array(
        'description' => 'Unique Key: Universally unique identifier for this entity.',
        'type' => 'varchar',
        'length' => 128,
        'not null' => FALSE,
      ),
      'type' => array(
        'description' => 'The type of this checklist.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'langcode' => array(
        'description' => 'The {language}.langcode of the original variant of this checklist.',
        'type' => 'varchar',
        'length' => 12,
        'not null' => TRUE,
        'default' => '',
      ),
      'name' => array(
        'description' => 'The name of the checklist.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'user_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => NULL,
        'description' => 'The {users}.uid of the associated user.',
      ),
      'checkbox_field' => array(
        'description' => 'Additional field for the checkbox entity.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => FALSE,
        'default' => '',
      ),
    ),
    'primary key' => array('ciid'),
    'unique keys' => array(
      'uuid' => array('uuid'),
    ),
  );
  return $schema;
}
?>