id: taxonomy_term.forum_container
uuid: babf2ba1-505f-4c71-8a07-7be19f4fb9f3
status: true
langcode: en
name: forum_container
type: list_boolean
settings:
  allowed_values:
    - ''
    - ''
  allowed_values_function: ''
module: options
entity_type: taxonomy_term
locked: true
cardinality: 1
translatable: false
indexes: {  }
