id: taxonomy_term.forums
uuid: c1c3d577-5517-4a43-a334-52884bb3b638
targetEntityType: taxonomy_term
bundle: forums
types:
  - 'sioc:Container'
  - 'sioc:Forum'
fieldMappings:
  name:
    properties:
      - 'schema:name'
  description:
    properties:
      - 'schema:description'
