id: node.field_tags
uuid: 60db47f4-54fb-4c86-a439-5769fbda4bd1
name: field_tags
entity_type: node
type: taxonomy_term_reference
module: taxonomy
settings:
  allowed_values:
    -
      vocabulary: tags
      parent: 0
locked: false
cardinality: -1
translatable: false
indexes:
  target_id:
    - target_id
status: true
langcode: und
