format: full_html
name: 'Full HTML'
uuid: 3d5d6be5-ac96-4a1b-bc00-c8725edead3c
status: true
weight: 1
roles:
  - administrator
cache: true
filters:
  filter_caption:
    id: filter_caption
    provider: filter
    status: true
    weight: 9
    settings: {  }
  filter_htmlcorrector:
    id: filter_htmlcorrector
    provider: filter
    status: true
    weight: 10
    settings: {  }
langcode: en
