type: article
uuid: 38fcdfbf-92a0-43d3-af30-8395cba668d4
name: Article
description: 'Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: 1
    options:
      status: true
      promote: true
      sticky: false
      revision: false
    submitted: true
status: true
langcode: en
