id: taxonomy_term.tags
uuid: 0ed6d2c7-f443-4a2b-b900-e4cfaae93489
targetEntityType: taxonomy_term
bundle: tags
types:
  - 'schema:Thing'
fieldMappings:
  name:
    properties:
      - 'schema:name'
  description:
    properties:
      - 'schema:description'
