id: node.page
uuid: 1f5c11e7-b657-4dd1-a100-b309d50271e7
targetEntityType: node
bundle: page
types:
  - 'schema:WebPage'
fieldMappings:
  title:
    properties:
      - 'schema:name'
  created:
    properties:
      - 'schema:dateCreated'
    datatype_callback:
      callable: 'date_iso8601'
  changed:
    properties:
      - 'schema:dateModified'
    datatype_callback:
      callable: 'date_iso8601'
  body:
    properties:
      - 'schema:text'
  uid:
    properties:
      - 'schema:author'
    mapping_type: 'rel'
  comment_count:
    properties:
      - 'schema:interactionCount'
    datatype_callback:
      callable: 'Drupal\rdf\SchemaOrgDataConverter::interactionCount'
      arguments:
        interaction_type: 'UserComments'
