id: stark_admin
theme: stark
weight: 1
status: true
langcode: en
region: sidebar_first
plugin: 'system_menu_block:admin'
settings:
  label: Administration
  module: system
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types: {  }
