type: book
uuid: c5ca890d-7db7-4c45-bf0f-0a12430923ff
name: 'Book page'
description: '<em>Books</em> have a built-in hierarchical navigation. Use for handbooks or tutorials.'
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: 1
    options:
      status: true
      # Not promoted to front page.
      promote: false
      sticky: false
      revision: false
    submitted: true
status: true
langcode: en
