<?php
/**
 * @file
 *
 * Example usage of the cw_tool models and controllers and utils.
 */

use CW\Controller\EntityControllerFactory;
use CW\Util\EntityBatchSaver;
use CW\Util\SimpleList;

require_once __DIR__ . '/vendor/autoload.php';

/**
 * Implements hook_cw_tool_service_container_definition_alter().
 * @param \CW\Util\SimpleList $collection
 */
function cw_tool_example_cw_tool_service_container_definition_alter(SimpleList $collection) {
  $collection->add(__DIR__ . '/config');
}

/**
 * Implements hook_init().
 */
function cw_tool_example_init() {
  /** @var EntityControllerFactory $articleFactory */
  $articleFactory = cw_tool_get_container()->get('cw.article.controller.factory');
  $article = $articleFactory->initWithId(1);
  drupal_set_message($article->getTitle());

  $article->updateTitle();

  /** @var EntityBatchSaver $nodeBatchSaver */
  $nodeBatchSaver = cw_tool_get_container()->get('cw.node-batch-saver');
  $nodeBatchSaver->saveAll();
}
