services:
  cw.logger:
    class: Drupal\PSR3\Logger\Watchdog

  cw.identity-map:
    class: CW\Util\LocalProcessIdentityMap

  cw.object-handler.drupal:
    class: CW\Model\DrupalObjectHandler

  cw.node-controller.factory:
    class: CW\Controller\NodeControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-handler.drupal
      - 'CW\Controller\NodeController'
      - 'CW\Model\NodeModel'
      - 'node'

  cw.user-controller.factory:
    class: CW\Controller\UserControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-handler.drupal
      - 'CW\Controller\UserController'
      - 'CW\Model\UserModel'
      - 'user'

  cw.node-batch-saver:
    class: CW\Util\EntityBatchSaver
    arguments:
      - @cw.identity-map
      - @cw.logger
