services:
  entity.loader:
    class: CW\Util\EntityLocalProcessIdentityMap
    arguments:
      - 'CW\Model\EntityModel'

  entity.controller.factory:
    class: CW\Controller\EntityControllerFactory
    arguments:
      - @entity.loader
      - 'CW\Controller\BasicEntityController'

#  entity.controller:
#    class: CW\Controller\BasicEntityController