services:
  cw.identity-map:
    class: CW\Util\LocalProcessIdentityMap

  cw.object-loader.drupal:
    class: CW\Model\DrupalObjectLoader

  cw.node-controller.factory:
    class: CW\Controller\EntityControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-loader.drupal
      - 'CW\Controller\BasicEntityController'
      - 'CW\Model\EntityModel'
      - 'node'

  cw.node-batch-saver:
    class: CW\Util\EntityBatchSaver
    arguments:
      - @cw.identity-map
