services:
  cw.logger:
    class: Drupal\PSR3\Logger\Watchdog

  cw.identity-map:
    class: CW\Util\LocalProcessIdentityMap

  cw.object-handler.drupal:
    class: CW\Model\DrupalObjectHandler

  cw.node-controller.factory:
    class: CW\Factory\EntityControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-handler.drupal
      - 'CW\Controller\NodeController'
      - 'node'
      - @cw.logger

  cw.user-controller.factory:
    class: CW\Factory\UserControllerFactory
    arguments:
      - @cw.identity-map
      - @cw.object-handler.drupal
      - 'CW\Controller\UserController'
      - 'user'
      - @cw.logger

  cw.node-batch-saver:
    class: CW\Util\EntityBatchSaver
    arguments:
      - @cw.identity-map
      - @cw.logger

  cw.variable-manager:
    class: CW\Manager\VariableManager
    arguments:
      - @cw.logger
