services:
  identity-map:
    class: CW\Util\LocalProcessIdentityMap

  node.controller.factory:
    class: CW\Controller\EntityControllerFactory
    arguments:
      - @identity-map
      - 'CW\Controller\BasicEntityController'
      - 'CW\Model\EntityModel'
      - 'node'
