# Schema for the configuration files of the Filter module.

filter.settings:
  type: mapping
  label: 'Filter settings'
  mapping:
    fallback_format:
      type: string
      label: 'Fallback text format'
    always_show_fallback_choice:
      type: boolean
      label: 'Always show fallback choice'

filter.format.*:
  type: mapping
  label: 'Text formats'
  mapping:
    format:
      type: string
      label: 'Machine name'
    name:
      type: label
      label: 'Name'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Enabled'
    weight:
      type: integer
      label: 'Weight'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        - type: string
          label: 'Role'
    cache:
      type: boolean
      label: 'Cache'
    filters:
      type: sequence
      label: 'Enabled filters'
      sequence:
        - type: filter
    langcode:
      type: string
      label: 'Default language'

filter_settings.*:
  type: sequence
  label: 'Filter settings'
  sequence:
    - type: string
      label: 'Value'

filter_settings.filter_html:
  type: filter
  label: 'Filter HTML'
  mapping:
    allowed_html:
      type: string
      label: 'Allowed HTML'
    filter_html_help:
      type: boolean
      label: 'HTML help'
    filter_html_nofollow:
      type: boolean
      label: 'HTML nofollow'


filter_settings.filter_url:
  type: filter
  label: 'Filter URL'
  mapping:
    filter_url_length:
      type: integer
      label: 'URL length'
