# Every site requires at least one text format as fallback format that
# - is accessible to all users.
# - is secure, using very basic formatting only.
# - may be modified by installation profiles to have other properties.
format: plain_text
name: 'Plain text'
uuid: 7dd77dca-6a80-4538-b10d-133fa66d42f0
status: true
weight: 10
roles:
  - anonymous
  - authenticated
cache: true
filters:
  # Escape all HTML.
  filter_html_escape:
    id: filter_html_escape
    provider: filter
    status: true
    weight: -10
    settings: {  }
  # Convert URLs into links.
  filter_url:
    id: filter_url
    provider: filter
    status: true
    weight: 0
    settings:
      filter_url_length: 72
  # Convert linebreaks into paragraphs.
  filter_autop:
    id: filter_autop
    provider: filter
    status: true
    weight: 0
    settings: {  }
langcode: en
